version: "3.8"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - TZ=Asia/Seoul
      - GENERIC_TIMEZONE=Asia/Seoul
      - NODE_FUNCTION_ALLOW_EXTERNAL=puppeteer
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
